<script setup lang="ts">
import { ref, watch } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { FilePlus2, ReceiptText, Search, UserPlus } from 'lucide-vue-next'
import ClinicLayout from '@/Layouts/ClinicLayout.vue'

interface QuoteRow { id: string; quote_number: string; alternative_name: string; status: string; grand_total: number; created_at: string; prospect_first_name: string | null; prospect_last_name: string | null; patient: { full_name: string; record_number: string } | null; professional: { full_name: string } | null; items: unknown[] }
interface PaginatedQuotes { data: QuoteRow[]; current_page: number; last_page: number; total: number; prev_page_url: string | null; next_page_url: string | null }
const props = defineProps<{ quotes: PaginatedQuotes; filters: { search?: string; status?: string; type?: string } }>()
const search = ref(props.filters.search || '')
const status = ref(props.filters.status || '')
const type = ref(props.filters.type || '')
let timer: ReturnType<typeof setTimeout>
watch([search, status, type], () => { clearTimeout(timer); timer = setTimeout(() => router.get('/quotes', { search: search.value || undefined, status: status.value || undefined, type: type.value || undefined }, { preserveState: true, replace: true }), 250) })
const money = (value: number) => new Intl.NumberFormat('es-DO', { style: 'currency', currency: 'DOP' }).format(value || 0)
const date = (value: string) => new Intl.DateTimeFormat('es-DO', { dateStyle: 'medium' }).format(new Date(value))
const customer = (quote: QuoteRow) => quote.patient?.full_name || `${quote.prospect_first_name || ''} ${quote.prospect_last_name || ''}`.trim()
const statusLabel = (value: string) => ({ draft: 'Borrador', presented: 'Presentado', approved: 'Aprobado', partially_approved: 'Parcial', rejected: 'Rechazado', converted: 'Con plan' }[value] || value)
</script>

<template>
    <Head title="Centro de presupuestos" />
    <ClinicLayout>
        <div class="mx-auto max-w-[1450px] space-y-5 p-4 md:p-7">
            <header class="flex flex-col justify-between gap-4 border-b border-[#D8E0DE] pb-5 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-[#006B63]">Gestión comercial clínica</p><h1 class="mt-1 text-3xl font-bold text-[#131B2E]">Centro de presupuestos</h1><p class="mt-1 text-sm text-[#667085]">Pacientes y prospectos en un solo lugar.</p></div><div class="flex flex-wrap gap-2"><Link href="/patients/create" class="inline-flex h-10 items-center gap-2 border border-[#9AAEAA] bg-white px-4 text-sm font-semibold text-[#005C55]"><UserPlus class="h-4 w-4" /> Nuevo paciente</Link><Link href="/quotes/quick-create" class="inline-flex h-10 items-center gap-2 rounded-md bg-[#005C55] px-4 text-sm font-semibold text-white"><FilePlus2 class="h-4 w-4" /> Cotización rápida</Link></div></header>
            <section class="grid gap-3 border border-[#BDC9C6] bg-white p-4 md:grid-cols-[1fr_190px_190px]"><label class="relative"><Search class="absolute left-3 top-3 h-4 w-4 text-[#667085]" /><input v-model="search" class="h-10 w-full border border-[#9AAEAA] pl-9 pr-3 text-sm" placeholder="Buscar número, nombre o expediente…" /></label><select v-model="type" class="h-10 border border-[#9AAEAA] bg-white px-3 text-sm"><option value="">Todos los tipos</option><option value="patient">Pacientes</option><option value="prospect">Prospectos</option></select><select v-model="status" class="h-10 border border-[#9AAEAA] bg-white px-3 text-sm"><option value="">Todos los estados</option><option value="draft">Borrador</option><option value="presented">Presentado</option><option value="converted">Con plan</option><option value="rejected">Rechazado</option></select></section>
            <section v-if="quotes.data.length" class="overflow-hidden border border-[#BDC9C6] bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-[#F2F6F5] text-xs font-bold uppercase tracking-[0.08em] text-[#455653]"><tr><th class="px-4 py-3">Presupuesto</th><th class="px-4 py-3">Persona</th><th class="px-4 py-3">Profesional</th><th class="px-4 py-3 text-center">Ítems</th><th class="px-4 py-3 text-right">Total</th><th class="px-4 py-3 text-right">Estado</th></tr></thead><tbody class="divide-y divide-[#D8E0DE]"><tr v-for="quote in quotes.data" :key="quote.id" class="hover:bg-[#F8FAFC]"><td class="px-4 py-4"><Link :href="`/quotes/${quote.id}`" class="font-mono font-bold text-[#006B63]">{{ quote.quote_number }}</Link><p class="mt-1 text-xs text-[#667085]">{{ quote.alternative_name }} · {{ date(quote.created_at) }}</p></td><td class="px-4 py-4"><p class="font-semibold text-[#131B2E]">{{ customer(quote) }}</p><span v-if="quote.patient" class="font-mono text-xs text-[#667085]">{{ quote.patient.record_number }}</span><span v-else class="mt-1 inline-block bg-violet-50 px-2 py-0.5 text-xs font-bold text-violet-700">Prospecto</span></td><td class="px-4 py-4 text-[#52615E]">{{ quote.professional?.full_name || 'Sin asignar' }}</td><td class="px-4 py-4 text-center font-mono">{{ quote.items.length }}</td><td class="px-4 py-4 text-right font-mono font-bold">{{ money(quote.grand_total) }}</td><td class="px-4 py-4 text-right"><span class="bg-[#F2F6F5] px-2 py-1 text-xs font-bold text-[#455653]">{{ statusLabel(quote.status) }}</span></td></tr></tbody></table></div><footer class="flex items-center justify-between border-t border-[#D8E0DE] p-4 text-sm"><span>{{ quotes.total }} presupuestos</span><div class="flex gap-2"><Link v-if="quotes.prev_page_url" :href="quotes.prev_page_url" class="border border-[#9AAEAA] px-3 py-2">Anterior</Link><Link v-if="quotes.next_page_url" :href="quotes.next_page_url" class="border border-[#9AAEAA] px-3 py-2">Siguiente</Link></div></footer></section>
            <section v-else class="grid min-h-64 place-items-center border border-dashed border-[#9AAEAA] bg-white p-10 text-center"><div><ReceiptText class="mx-auto h-10 w-10 text-[#9AAEAA]" /><h2 class="mt-3 font-bold text-[#131B2E]">No hay presupuestos con estos filtros</h2><p class="mt-1 text-sm text-[#667085]">Crea una cotización rápida aun si la persona todavía no es paciente.</p><Link href="/quotes/quick-create" class="mt-4 inline-flex h-10 items-center rounded-md bg-[#005C55] px-4 text-sm font-semibold text-white">Cotización rápida</Link></div></section>
        </div>
    </ClinicLayout>
</template>
