<script setup lang="ts">
import { computed } from 'vue'
import { Head, Link, useForm } from '@inertiajs/vue3'
import { appUrl } from '@/lib/url'
import { ArrowLeft, CalendarDays, CheckCircle2, ClipboardList, FileText, Link2, Printer, ShieldCheck, Stethoscope, UserPlus, UserRound, XCircle } from 'lucide-vue-next'
import ClinicLayout from '@/Layouts/ClinicLayout.vue'

interface MedicalHistory { allergies: string[] | null; systemic_conditions: string[] | null }
interface PatientDetails { id: string; record_number: string; full_name: string; medical_history?: MedicalHistory | null }
interface PatientCandidate { id: string; record_number: string; full_name: string; phone: string | null; email: string | null }
interface ProfessionalDetails { id: string; full_name: string }
interface QuoteItemDetails { id: string; tooth_number: number | null; surface: string; phase?: number; unit_price: number; quantity: number; discount_percentage: number; total: number; procedure: { name: string; code: string | null } }
interface QuoteDetails {
    id: string; patient_id: string | null; prospect_first_name: string | null; prospect_last_name: string | null
    prospect_phone: string | null; prospect_email: string | null; quote_number: string; version: number; alternative_name: string
    status: 'draft' | 'presented' | 'approved' | 'partially_approved' | 'rejected' | 'converted'
    subtotal: number; discount_total: number; tax_total: number; grand_total: number; notes: string | null
    expires_at: string | null; approved_at: string | null; approved_by_name: string | null; created_at: string
    patient: PatientDetails | null; professional?: ProfessionalDetails | null; items: QuoteItemDetails[]
    treatment_plan?: { id: string; status: string; progress_percentage: number } | null
}

const props = defineProps<{ quote: QuoteDetails; prospectCandidates: PatientCandidate[] }>()
const isProspect = computed(() => !props.quote.patient_id || !props.quote.patient)
const customerName = computed(() => props.quote.patient?.full_name || `${props.quote.prospect_first_name || ''} ${props.quote.prospect_last_name || ''}`.trim())
const approveForm = useForm({ approved_by_name: props.quote.patient?.full_name || '' })
const rejectForm = useForm({})
const conversionForm = useForm({ first_name: props.quote.prospect_first_name || '', last_name: props.quote.prospect_last_name || '', phone: props.quote.prospect_phone || '', email: props.quote.prospect_email || '', identification_type: '', identification_number: '' })
const money = (value: number) => new Intl.NumberFormat('es-DO', { style: 'currency', currency: 'USD' }).format(value || 0)
const date = (value: string | null) => value ? new Intl.DateTimeFormat('es-DO', { dateStyle: 'medium' }).format(new Date(value)) : 'No definido'
const statusLabel = (status: QuoteDetails['status']) => ({ draft: 'Borrador', presented: 'Presentado', approved: 'Aprobado', partially_approved: 'Aprobación parcial', rejected: 'Rechazado', converted: 'Convertido a plan' })[status]
const statusClass = (status: QuoteDetails['status']) => status === 'converted' || status === 'approved' ? 'bg-[#D8ECE9] text-[#006B63] border-[#9BCDC7]' : status === 'rejected' ? 'bg-red-50 text-red-700 border-red-200' : 'bg-amber-50 text-amber-800 border-amber-200'
function approveQuote() { if (window.confirm(`¿Aprobar ${props.quote.quote_number} y generar el plan de tratamiento?`)) approveForm.post(appUrl(`/quotes/${props.quote.id}/approve`)) }
function rejectQuote() { if (window.confirm(`¿Marcar ${props.quote.quote_number} como rechazado?`)) rejectForm.post(appUrl(`/quotes/${props.quote.id}/reject`)) }
function linkPatient(patientId: string) { useForm({ existing_patient_id: patientId }).post(`/quotes/${props.quote.id}/convert-to-patient`) }
function createPatient() { conversionForm.post(appUrl(`/quotes/${props.quote.id}/convert-to-patient`)) }
function triggerPrint() { window.print() }
</script>

<template>
    <Head :title="`Presupuesto ${quote.quote_number} — ${customerName}`" />
    <ClinicLayout>
        <div class="mx-auto max-w-[1400px] space-y-5 p-4 md:p-7">
            <section class="border border-[#D8E0DE] bg-white p-4 md:p-5 print:hidden">
                <div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-center">
                    <div class="flex items-center gap-3"><div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#D8ECE9] text-lg font-bold text-[#006B63]">{{ customerName.charAt(0) }}</div><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-semibold text-[#131B2E]">{{ customerName }}</h2><span v-if="quote.patient" class="font-mono text-xs text-[#667085]">{{ quote.patient.record_number }}</span><span v-else class="border border-violet-200 bg-violet-50 px-2 py-1 text-xs font-bold text-violet-700">Prospecto</span></div><p v-if="isProspect" class="mt-1 text-xs text-[#667085]">{{ quote.prospect_phone || 'Sin teléfono' }} · {{ quote.prospect_email || 'Sin correo' }}</p><div v-else class="mt-1 flex flex-wrap gap-1.5"><span v-for="allergy in quote.patient?.medical_history?.allergies || []" :key="allergy" class="bg-red-50 px-2 py-1 text-xs font-semibold text-red-700">Alergia: {{ allergy }}</span><span v-for="condition in quote.patient?.medical_history?.systemic_conditions || []" :key="condition" class="bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-800">{{ condition }}</span></div></div></div>
                    <div v-if="quote.patient" class="flex flex-wrap gap-2"><Link :href="`/patients/${quote.patient_id}`" class="inline-flex h-10 items-center gap-2 border border-[#9AAEAA] bg-white px-4 text-sm font-semibold text-[#005C55]"><UserRound class="h-4 w-4" /> Ficha 360</Link><Link :href="`/patients/${quote.patient_id}/treatment-plans`" class="inline-flex h-10 items-center gap-2 border border-[#9AAEAA] bg-white px-4 text-sm font-semibold text-[#005C55]"><ClipboardList class="h-4 w-4" /> Tratamientos</Link></div>
                </div>
            </section>

            <section v-if="isProspect" class="border border-violet-200 bg-violet-50 p-5 print:hidden">
                <div class="flex items-start gap-3"><UserPlus class="mt-0.5 h-5 w-5 text-violet-700" /><div><h2 class="font-bold text-[#131B2E]">Convierte el prospecto antes de aprobar</h2><p class="mt-1 text-sm text-[#52615E]">Vincula una ficha existente o crea una historia clínica conservando esta cotización.</p></div></div>
                <div v-if="prospectCandidates.length" class="mt-4 border border-amber-200 bg-amber-50 p-4"><p class="text-sm font-bold text-amber-900">Posibles pacientes existentes</p><div class="mt-3 grid gap-2 md:grid-cols-2"><button v-for="candidate in prospectCandidates" :key="candidate.id" type="button" class="flex items-center justify-between border border-amber-300 bg-white p-3 text-left text-sm" @click="linkPatient(candidate.id)"><span><strong class="text-[#131B2E]">{{ candidate.full_name }}</strong><small class="mt-1 block text-[#667085]">{{ candidate.record_number }} · {{ candidate.phone || candidate.email || 'Sin contacto' }}</small></span><Link2 class="h-4 w-4 text-[#006B63]" /></button></div></div>
                <form class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3" @submit.prevent="createPatient">
                    <label class="text-xs font-bold text-[#455653]">Nombre *<input v-model="conversionForm.first_name" required maxlength="100" class="mt-1 h-10 w-full border border-[#9AAEAA] bg-white px-3 text-sm font-normal" /></label><label class="text-xs font-bold text-[#455653]">Apellido *<input v-model="conversionForm.last_name" required maxlength="100" class="mt-1 h-10 w-full border border-[#9AAEAA] bg-white px-3 text-sm font-normal" /></label><label class="text-xs font-bold text-[#455653]">Teléfono<input v-model="conversionForm.phone" maxlength="50" class="mt-1 h-10 w-full border border-[#9AAEAA] bg-white px-3 text-sm font-normal" /></label><label class="text-xs font-bold text-[#455653]">Correo<input v-model="conversionForm.email" type="email" maxlength="255" class="mt-1 h-10 w-full border border-[#9AAEAA] bg-white px-3 text-sm font-normal" /></label><label class="text-xs font-bold text-[#455653]">Tipo de identificación<select v-model="conversionForm.identification_type" class="mt-1 h-10 w-full border border-[#9AAEAA] bg-white px-3 text-sm font-normal"><option value="">Sin especificar</option><option value="cedula">Cédula</option><option value="passport">Pasaporte</option></select></label><label class="text-xs font-bold text-[#455653]">Identificación<input v-model="conversionForm.identification_number" maxlength="100" class="mt-1 h-10 w-full border border-[#9AAEAA] bg-white px-3 text-sm font-normal" /></label>
                    <button type="submit" :disabled="conversionForm.processing" class="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-violet-700 px-4 text-sm font-semibold text-white disabled:opacity-50 md:col-span-2 xl:col-span-3"><UserPlus class="h-4 w-4" /> Crear paciente y vincular</button>
                </form>
            </section>

            <header class="flex flex-col justify-between gap-4 border-b border-[#D8E0DE] pb-5 lg:flex-row lg:items-end"><div><div class="flex flex-wrap items-center gap-2"><p class="text-xs font-bold uppercase tracking-[0.16em] text-[#006B63]">Presupuesto odontológico</p><span class="border px-2 py-1 text-xs font-semibold" :class="statusClass(quote.status)">{{ statusLabel(quote.status) }}</span></div><h1 class="mt-2 text-2xl font-bold text-[#131B2E] md:text-3xl">{{ quote.quote_number }} · {{ quote.alternative_name }}</h1><p class="mt-1 text-sm text-[#667085]">Versión {{ quote.version }} · Creado {{ date(quote.created_at) }}</p></div><div class="flex flex-wrap gap-2 print:hidden"><button type="button" class="inline-flex h-10 items-center gap-2 border border-[#BDC9C6] bg-white px-4 text-sm font-semibold text-[#131B2E] hover:bg-[#F8FAFC] transition shadow-xs" @click="triggerPrint"><Printer class="h-4 w-4 text-[#505F76]" /> Imprimir Presupuesto</button><Link :href="appUrl('/quotes')" class="inline-flex h-10 items-center gap-2 border border-[#9AAEAA] bg-white px-4 text-sm font-semibold text-[#005C55]"><ArrowLeft class="h-4 w-4" /> Presupuestos</Link><Link v-if="quote.treatment_plan" :href="`/treatment-plans/${quote.treatment_plan.id}`" class="inline-flex h-10 items-center gap-2 rounded-md bg-[#005C55] px-4 text-sm font-semibold text-white"><ClipboardList class="h-4 w-4" /> Ver plan de tratamiento</Link><button v-if="quote.status === 'draft' || quote.status === 'presented'" type="button" class="inline-flex h-10 items-center gap-2 border border-red-300 bg-white px-4 text-sm font-semibold text-red-700" :disabled="rejectForm.processing" @click="rejectQuote"><XCircle class="h-4 w-4" /> Rechazar</button><button v-if="!isProspect && (quote.status === 'draft' || quote.status === 'presented')" type="button" class="inline-flex h-10 items-center gap-2 rounded-md bg-[#005C55] px-4 text-sm font-semibold text-white disabled:opacity-50" :disabled="approveForm.processing" @click="approveQuote"><CheckCircle2 class="h-4 w-4" /> Aprobar y generar plan</button></div></header>

            <section class="grid gap-4 md:grid-cols-3"><article class="border border-[#D8E0DE] bg-white p-4"><p class="text-xs font-bold uppercase tracking-[0.12em] text-[#667085]">Profesional tratante</p><p class="mt-2 flex items-center gap-2 font-semibold text-[#131B2E]"><Stethoscope class="h-4 w-4 text-[#006B63]" /> {{ quote.professional?.full_name || 'Sin asignar' }}</p></article><article class="border border-[#D8E0DE] bg-white p-4"><p class="text-xs font-bold uppercase tracking-[0.12em] text-[#667085]">Vigencia</p><p class="mt-2 flex items-center gap-2 font-semibold text-[#131B2E]"><CalendarDays class="h-4 w-4 text-[#006B63]" /> {{ date(quote.expires_at) }}</p></article><article class="border border-[#D8E0DE] bg-white p-4"><p class="text-xs font-bold uppercase tracking-[0.12em] text-[#667085]">Aprobación</p><p class="mt-2 flex items-center gap-2 font-semibold text-[#131B2E]"><ShieldCheck class="h-4 w-4 text-[#006B63]" /> {{ isProspect ? 'Requiere paciente' : quote.approved_by_name || (quote.approved_at ? 'Firmante no registrado' : 'Pendiente') }}</p></article></section>

            <section class="overflow-hidden border border-[#BDC9C6] bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="border-b border-[#BDC9C6] bg-[#F2F6F5] text-xs font-bold uppercase tracking-[0.08em] text-[#455653]"><tr><th class="px-4 py-3">Procedimiento</th><th class="px-4 py-3 text-center">Fase</th><th class="px-4 py-3">Pieza</th><th class="px-4 py-3 text-center">Cant.</th><th class="px-4 py-3 text-right">Precio unit.</th><th class="px-4 py-3 text-right">Desc.</th><th class="px-4 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-[#E2E8F0]"><tr v-for="item in quote.items" :key="item.id" class="hover:bg-[#F8FAFC]"><td class="px-4 py-4"><p class="font-semibold text-[#131B2E]">{{ item.procedure.name }}</p><p class="mt-0.5 font-mono text-xs text-[#667085]">{{ item.procedure.code || 'Sin código' }} · {{ item.surface || 'Todas las superficies' }}</p></td><td class="px-4 py-4 text-center"><span class="px-2 py-0.5 bg-[#005C55]/10 text-[#005C55] font-semibold text-xs rounded-md">Fase {{ item.phase || 1 }}</span></td><td class="px-4 py-4 font-mono font-bold text-[#006B63]">{{ item.tooth_number || 'General' }}</td><td class="px-4 py-4 text-center">{{ item.quantity }}</td><td class="px-4 py-4 text-right font-mono">{{ money(item.unit_price) }}</td><td class="px-4 py-4 text-right font-mono">{{ item.discount_percentage }}%</td><td class="px-4 py-4 text-right font-mono font-bold">{{ money(item.total) }}</td></tr></tbody></table></div><div class="grid border-t border-[#BDC9C6] bg-[#F8FAFC] lg:grid-cols-[1fr_360px]"><div class="border-b border-[#D8E0DE] p-5 lg:border-b-0 lg:border-r"><p class="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[#455653]"><FileText class="h-4 w-4" /> Notas</p><p class="mt-3 whitespace-pre-line text-sm leading-6 text-[#455653]">{{ quote.notes || 'No se registraron notas para este presupuesto.' }}</p></div><dl class="space-y-3 p-5 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd class="font-mono">{{ money(quote.subtotal) }}</dd></div><div class="flex justify-between"><dt>Descuentos</dt><dd class="font-mono text-emerald-700">− {{ money(quote.discount_total) }}</dd></div><div class="flex justify-between"><dt>Impuestos</dt><dd class="font-mono">{{ money(quote.tax_total) }}</dd></div><div class="flex items-end justify-between border-t border-[#BDC9C6] pt-4"><dt class="font-bold">Total estimado</dt><dd class="font-mono text-2xl font-bold text-[#005C55]">{{ money(quote.grand_total) }}</dd></div></dl></div></section>
        </div>
    </ClinicLayout>
</template>
